export const PAYMENT_METHODS_MODAL = "PAYMENT_METHODS_MODAL";

export const PLAIN_MESSAGE_MODAL = "PLAIN_MESSAGE_MODAL";

export const ADMIN_AUTHENTICATION_MODAL = "ADMIN_AUTHENTICATION_MODAL";

export const INVENTORY_ITEM = "INVENTORY_ITEM";
